package net.whzxt.zxtexam;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;

public class DBer extends SQLiteOpenHelper {
	public static final String T_ROUTE = "zxt_route";// 路线
	public static final String T_ROUTE_ITEM = "zxt_route_item";// 路线项目
	public static final String T_ITEM = "zxt_item";// 项目
	public static final String T_ITEM_ERR = "zxt_item_err";// 项目扣分项
	public static final String T_ITEM_ACTION = "zxt_item_action";// 项目动作

	public DBer(Context context, String name, CursorFactory factory, int version) {
		super(context, name, factory, version);
	}

	@Override
	public void onCreate(SQLiteDatabase db) {
		db.execSQL("CREATE TABLE IF NOT EXISTS " + T_ROUTE + " (routeid INTEGER PRIMARY KEY,name VARCHAR(20),tts VARCHAR(100),auto INTEGER)");
		db.execSQL("CREATE TABLE IF NOT EXISTS " + T_ROUTE_ITEM + " (routeid INTEGER,itemid INTEGER,lon FLOAT,lat FLOAT,xuhao INTEGER)");
		db.execSQL("CREATE TABLE IF NOT EXISTS " + T_ITEM + " (itemid INTEGER PRIMARY KEY,name VARCHAR(20),tts VARCHAR(100),timeout INTEGER,type INTEGER,xuhao INTEGER)");
		db.execSQL("CREATE TABLE IF NOT EXISTS " + T_ITEM_ERR + " (errid INTEGER PRIMARY KEY,itemid INTEGER,name VARCHAR(100),fenshu INTEGER)");
		db.execSQL("CREATE TABLE IF NOT EXISTS " + T_ITEM_ACTION + " (itemid INTEGER,dataid INTEGER,times INTEGER,min INTEGER,max INTEGER,errid INTEGER,step INTEGER)");
		
		// 默认值
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (0,'上车准备','上车准备',20,0,1)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (1,'起步','起步',20,0,2)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (2,'直线行驶','直线行驶',20,0,3)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (3,'向左变更车道','向左变更车道',20,0,4)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (4,'通过路口','通过路口',20,0,6)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (5,'通过人行横道线','通过人行横道线',20,0,7)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (6,'会车','会车',20,0,10)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (7,'超车','超车',20,0,11)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (8,'靠边停车','靠边停车',20,0,15)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (9,'掉头','掉头',20,0,16)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (11,'夜间在没有路灯、照明不良条件下行驶','夜间在没有路灯、照明不良条件下行驶',5,1,1)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (12,'请将前大灯换成远光','请将前大灯换成远光',5,1,2)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (13,'夜间同向近距离跟车行驶','夜间同向近距离跟车行驶',5,1,3)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (14,'夜间通过急弯、坡路、拱桥、人行横道、或没有交通信号灯控制的路口','夜间通过急弯、坡路、拱桥、人行横道、或没有交通信号灯控制的路口',5,1,4)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (15,'夜间在窄路与非机动车会车','夜间在窄路与非机动车会车',5,1,5)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (16,'雾天行驶','雾天行驶',5,1,6)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (17,'夜间在道路上发生故障，妨碍交通又难以移动','夜间在道路上发生故障，妨碍交通又难以移动',5,1,7)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (18,'模拟夜间考试完成，请关闭所有灯光','模拟夜间考试完成，请关闭所有灯光',5,1,8)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (21,'加减档位','加减档位',20,0,12)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (22,'向右变更车道','向右变更车道',20,0,5)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (23,'路口左转弯','路口左转弯',20,0,13)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (24,'路口右转弯','路口右转弯',20,0,14)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (25,'通过学校区域','通过学校区域',20,0,8)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (26,'通过公共汽车站','通过公共汽车站',20,0,9)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (27,'夜间在窄桥与机动车会车','夜间在窄桥与机动车会车',5,1,9)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (0,0,'不绕车一周检查车辆外观及安全状况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (1,0,'打开车门前不观察后方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (2,1,'制动气压不足起步',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (3,1,'车门未关闭起步',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (4,1,'起步前，未通过后视镜并向左方侧头，观察左、后方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (5,1,'启动发动机时，变速器操纵杆未置于空挡(或者P挡)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (6,1,'发动机启动后，不及时松开启动开关',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (7,1,'不松驻车制动器起步',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (8,1,'道路交通情况复杂时起步不能合理使用喇叭',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (9,1,'起步时车辆发生闯动',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (10,1,'起步时，加速踏板控制不当，致使发动机转速过高',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (11,1,'启动发动机前，不调整驾驶座椅、后视镜、检查仪表',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (12,2,'方向控制不稳，不能保持车辆直线运动状态',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (13,2,'不了解车辆行驶速度',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (14,2,'未及时发现路面障碍物，未及时采取减速措施',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (15,3,'变更车道时，判断车辆安全距离不合理，妨碍其他车辆正常行驶',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (16,3,'连续变更两条以上车道',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (17,4,'通过路口前未减速慢行',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (18,4,'遇有路口交通阻塞时进入路口，将车辆停在路口内等候',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (19,4,'不按规定避让行人和优先通过的车辆',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (20,4,'左转通过路口时，未靠路口中心点左侧转弯',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (21,5,'不按规定减速慢行',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (22,5,'未停车礼让行人',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (23,6,'在没有中心隔离设施或者中心线的道路上会车时，不减速靠右行驶，并与其他车辆、行人或者非机动车未保持安全距离',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (24,6,'横向安全间距判断差，紧急转向避让相对方向来车',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (25,7,'超车时机选择不合理，影响其他车辆正常行驶',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (26,7,'超车时未与被超越车辆保持安全距离',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (27,7,'超车后急转向驶回本车道，妨碍被超车辆正常行驶',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (28,7,'从右侧超车',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (29,7,'当后车发出超车信号时，具备让车条件不减速靠右让行',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (30,8,'停车前，不通过内、外后视镜观察后方和右侧交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (31,8,'停车后，车身超过道路右侧边缘线或者人行道边缘',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (32,8,'停车后，在车内开门前不侧头观察侧后方和左侧交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (33,8,'停车后，车身距离道路右侧边缘线或者人行道边缘大于30厘米',20)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (34,8,'停车后，未拉紧驻车制动器',20)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (35,8,'拉紧驻车制动器前放松行车制动踏板',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (36,8,'下车后不关车门',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (37,8,'下车前不将发动机熄火',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (38,8,'夜间在路边临时停车不关闭前照灯或不开启警示灯',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (39,9,'不能正确观察交通情况选择掉头时机',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (40,9,'掉头地点选择不当',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (41,9,'掉头时，妨碍正常行驶的其他车辆和行人通行',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (43,13,'同方向近距离跟车行驶时，使用远光灯',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (44,14,'通过急弯、坡路、拱桥、人行横道或者没有交通信号灯控制的路口时，不交替使用远、近光灯示意',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (45,15,'会车时不按规定使用灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (49,11,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (50,12,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (51,13,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (52,14,'夜间通过坡路、拱桥时，没有交替使用远、近光灯示意',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (53,14,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (54,17,'在路边临时停车没有关闭前照灯(1)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (55,18,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (56,16,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (57,17,'在路边临时停车没有开启警示灯(2)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (58,17,'在路边临时停车没有开启警示灯(3)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (59,17,'在路边临时停车没有开启警示灯(4)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (60,17,'在路边临时停车没有关闭前照灯(5)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (61,21,'未按指令平稳加、减挡',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (62,21,'车辆运行速度和档位不匹配',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (63,3,'变更车道前，未通过内、外后视镜观察后方道路交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (64,3,'开启转向灯少于3秒',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (65,22,'变更车道时，判断车辆安全距离不合理，妨碍其他车辆正常行驶',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (66,22,'连续变更两条以上车道',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (67,22,'变更车道前，未通过内、外后视镜观察后方道路交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (68,22,'开启转向灯少于3秒',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (69,22,'未开启转向灯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (70,3,'未开启转向灯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (71,4,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (72,4,'转弯通过路口时，未观察侧前方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (73,23,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (74,23,'转弯通过路口时，未观察侧前方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (75,23,'未开启转向灯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (76,23,'开启转向灯少于3秒',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (77,23,'左转弯通过路口时，未靠路口中心点左侧转弯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (78,23,'遇有路口交通阻塞时进入路口，将车辆停在路口内等候',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (79,23,'未按规定减速或停车',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (80,24,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (81,24,'转弯通过路口时，未观察侧前方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (82,24,'未开启转向灯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (83,24,'开启转向灯少于3秒',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (84,24,'右转弯通过路口时，未靠路口中心点右侧转弯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (85,24,'遇有路口交通阻塞时进入路口，将车辆停在路口内等候',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (86,24,'未按规定减速或停车',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (87,5,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (88,25,'未按规定减速慢行',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (89,25,'未停车礼让行人',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (90,25,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (91,26,'未按规定减速慢行',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (92,26,'未停车礼让行人',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (93,26,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (94,9,'未开启转向灯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (95,9,'0',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (96,8,'未开启转向灯，扣10分。',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (97,8,'开启转向灯，少于3秒，扣10分',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (98,8,'考试员发出靠边停车后，未能在规定距离内停车的，不合格。',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (99,8,'拉紧驻车制动器前，放松行车制动踏板的，扣10分。',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (100,8,'下车前不将发动机熄火的，扣5分。',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (101,8,'下车不关闭车门的，不合格。',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (102,15,'会车时不按规定使用灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (104,11,'不能正确开启灯光(雾灯未关闭)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (105,22,'未开启转向灯(考试过程中熄火)',10)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (0,'随机路线','当前为随机路线,请点击考试项目开始考试',0)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (1,'模拟夜间灯光考试（人工）','下面将、进行模拟夜间行驶场景灯光、使用的考试，请按语音指令、在5秒内做出相应的灯光操作',1)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (2,'模拟夜间灯光考试一','下面将、进行模拟夜间行驶场景灯光、使用的考试，请按语音指令、在5秒内做出相应的灯光操作',1)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (3,'模拟夜间灯光考试二','下面将、进行模拟夜间行驶场景灯光、使用的考试，请按语音指令、在5秒内做出相应的灯光操作',1)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (4,'模拟夜间灯光考试三','下面将、进行模拟夜间行驶场景灯光、使用的考试，请按语音指令、在5秒内做出相应的灯光操作',1)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (5,'模拟夜间灯光考试四','下面将、进行模拟夜间行驶场景灯光、使用的考试，请按语音指令、在5秒内做出相应的灯光操作',1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,0,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,1,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,2,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,3,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,4,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,5,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,6,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,7,0,0,8)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,9,0,0,9)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,21,0,0,10)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,22,0,0,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,23,0,0,12)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,24,0,0,13)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,25,0,0,14)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,26,0,0,15)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,27,0,0,16)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,8,0,0,17)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,11,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,12,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,13,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,14,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,15,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,16,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,17,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,18,0,0,8)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,11,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,12,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,13,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,12,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,15,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,17,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,18,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,11,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,12,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,14,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,12,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,15,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,17,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,18,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,11,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,12,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,14,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,12,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,15,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,16,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,18,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,11,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,12,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,14,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,12,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,15,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,17,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,18,0,0,7)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,12,2,0,0,3,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,12,-1,0,0,3,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,21,0,0,1,3,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,20,0,0,500,3,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,12,-1,0,0,2,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,21,0,0,1,2,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,20,0,0,500,2,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,5,-2,0,0,7,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,12,-1,0,0,7,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,21,0,0,1,7,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,20,0,0,3000,7,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,5,1,0,0,10,5)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,12,-1,0,0,10,5)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,21,0,1,0,10,5)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,20,0,0,3000,10,5)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,5,1,0,0,13,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,12,1,0,0,13,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,21,0,30,0,13,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,20,0,100,3000,13,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,5,1,0,0,12,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,12,1,0,0,12,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,21,0,30,40,12,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,20,0,100,3000,12,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,31,0,-5,5,12,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (3,3,2,0,0,70,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (3,5,1,0,0,70,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (3,12,1,0,0,70,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (3,20,0,100,3000,70,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (4,5,1,0,0,17,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (4,7,2,0,0,17,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (4,12,1,0,0,17,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (4,20,0,100,300,17,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (5,5,1,0,0,21,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (5,7,2,0,0,21,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (5,12,1,0,0,21,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (5,20,0,100,3000,21,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,4,2,0,0,96,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,12,1,0,0,96,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,20,0,100,3000,96,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,5,1,0,0,999,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,12,1,0,0,98,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,21,0,0,1,98,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,20,0,100,3000,98,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,5,2,0,0,35,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,7,2,0,0,35,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,12,1,0,0,35,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,21,0,0,1,35,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,20,0,100,3000,35,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,5,2,0,0,37,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,6,0,0,0,999,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,20,0,0,100,37,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,5,2,0,0,36,5)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,12,2,0,0,36,5)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,20,0,0,100,36,5)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (9,3,2,0,0,94,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (9,5,1,0,0,94,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (9,12,1,0,0,94,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (9,20,0,100,3000,94,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (11,0,2,0,0,49,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (11,1,2,0,0,49,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (11,2,-2,0,0,49,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (11,6,2,0,0,49,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (11,9,-2,0,0,49,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (12,0,2,0,0,50,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (12,1,2,0,0,50,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (12,2,2,0,0,50,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (12,6,2,0,0,50,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (12,9,-2,0,0,50,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (13,0,2,0,0,51,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (13,1,2,0,0,43,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (13,2,-2,0,0,43,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (13,6,2,0,0,51,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (13,9,-2,0,0,51,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,2,2,0,0,52,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,2,-2,0,0,52,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,2,2,0,0,52,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,0,2,0,0,53,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,1,2,0,0,53,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,2,-2,0,0,53,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,6,2,0,0,53,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,9,-2,0,0,53,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (15,0,2,0,0,102,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (15,1,2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (15,2,-2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (15,6,2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (15,9,-2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,6,-2,0,0,56,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,6,2,0,0,56,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,6,-2,0,0,56,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,0,2,0,0,56,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,1,2,0,0,999,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,2,-2,0,0,56,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,6,2,0,0,56,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,9,2,0,0,56,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,6,-2,0,0,57,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,6,2,0,0,54,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,6,-2,0,0,57,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,0,2,0,0,60,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,1,-2,0,0,54,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,2,-2,0,0,54,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,6,2,0,0,59,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,9,-2,0,0,54,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (18,0,-2,0,0,55,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (18,1,-2,0,0,55,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (18,2,-2,0,0,55,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (18,6,-2,0,0,55,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (18,9,-2,0,0,55,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (21,5,1,0,0,61,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (21,12,1,0,0,61,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (21,20,0,100,3000,61,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (22,4,2,0,0,69,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (22,7,1,0,0,69,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (22,12,1,0,0,69,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (22,20,0,100,3000,105,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,5,1,0,0,79,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,7,2,0,0,79,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,12,1,0,0,79,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,20,0,100,3000,79,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,3,2,0,0,75,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,5,1,0,0,75,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,12,1,0,0,75,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,20,0,100,3000,75,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,5,1,0,0,86,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,7,2,0,0,86,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,12,1,0,0,86,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,20,0,100,3000,86,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,4,2,0,0,82,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,12,1,0,0,82,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,20,0,100,3000,82,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (25,5,1,0,0,88,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (25,7,2,0,0,88,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (25,12,1,0,0,88,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (25,20,0,100,3000,88,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (26,5,1,0,0,91,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (26,7,2,0,0,91,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (26,12,1,0,0,91,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (26,20,0,100,3000,91,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (27,0,2,0,0,102,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (27,1,2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (27,2,-2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (27,6,2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (27,9,-2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,7,2,0,0,2,3)");

	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
		db.execSQL("DROP TABLE IF EXISTS " + T_ROUTE);
		db.execSQL("DROP TABLE IF EXISTS " + T_ROUTE_ITEM);
		db.execSQL("DROP TABLE IF EXISTS " + T_ITEM);
		db.execSQL("DROP TABLE IF EXISTS " + T_ITEM_ERR);
		db.execSQL("DROP TABLE IF EXISTS " + T_ITEM_ACTION);
		onCreate(db);
	}
}