package net.whzxt.zxtexam;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;

public class DBer extends SQLiteOpenHelper {
	public static final String T_ROUTE = "zxt_route";// 路线
	public static final String T_ROUTE_ITEM = "zxt_route_item";// 路线项目
	public static final String T_ITEM = "zxt_item";// 项目
	public static final String T_ITEM_ERR = "zxt_item_err";// 项目扣分项
	public static final String T_ITEM_ACTION = "zxt_item_action";// 项目动作

	public DBer(Context context, String name, CursorFactory factory, int version) {
		super(context, name, factory, version);
	}

	@Override
	public void onCreate(SQLiteDatabase db) {
		db.execSQL("CREATE TABLE IF NOT EXISTS " + T_ROUTE + " (routeid INTEGER PRIMARY KEY,name VARCHAR(20),tts VARCHAR(100),auto INTEGER)");
		db.execSQL("CREATE TABLE IF NOT EXISTS " + T_ROUTE_ITEM + " (routeid INTEGER,itemid INTEGER,lon FLOAT,lat FLOAT,xuhao INTEGER)");
		db.execSQL("CREATE TABLE IF NOT EXISTS " + T_ITEM + " (itemid INTEGER PRIMARY KEY,name VARCHAR(20),tts VARCHAR(100),timeout INTEGER,type INTEGER,xuhao INTEGER)");
		db.execSQL("CREATE TABLE IF NOT EXISTS " + T_ITEM_ERR + " (errid INTEGER PRIMARY KEY,itemid INTEGER,name VARCHAR(100),fenshu INTEGER)");
		db.execSQL("CREATE TABLE IF NOT EXISTS " + T_ITEM_ACTION + " (itemid INTEGER,dataid INTEGER,times INTEGER,min INTEGER,max INTEGER,errid INTEGER,step INTEGER)");

		// 默认值
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (0,'上车准备','上车准备',20,0,1)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (1,'起步','请关闭发动机准备开始考试。请起步。',10,0,2)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (2,'直线行驶','请沿当前道路直线行驶并保持时速在35公里左右',7,0,3)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (3,'向左变更车道','请向左变更车道',10,0,4)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (22,'向右变更车道','请向右变更车道',10,0,5)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (38,'前方通过路口语音播报','前方请直行通过路口',1,0,6)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (4,'直行通过路口','、',7,0,8)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (5,'通过人行横道线','、',5,0,9)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (25,'通过学校区域','通过学校区域',5,0,9)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (26,'通过公共汽车站','前方通过公共汽车站',5,0,10)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (39,'减速让行','请减速让行',5,0,11)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (6,'会车','与机动车会车',10,0,12)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (7,'超车','请超越前方车辆',10,0,13)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (21,'加减档位','请换档',20,0,14)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (36,'前方路口左转语音播报','前方路口左转弯',1,0,15)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (23,'路口左转弯','、',10,0,16)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (37,'前方路口右转语音播报','前方路口右转弯',1,0,17)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (24,'路口右转弯','、',10,0,18)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (9,'掉头','请掉头行驶',10,0,19)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (8,'靠边停车','请靠边停车',30,0,20)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (11,'夜间在没有路灯、照明不良条件下行驶','夜间在没有路灯、照明不良条件下行驶',5,1,1)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (12,'请将前大灯换成远光','请将前大灯换成远光',5,1,2)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (13,'夜间同向近距离跟车行驶','夜间同向近距离跟车行驶',5,1,3)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (14,'夜间通过急弯、坡路、拱桥、人行横道、或没有交通信号灯控制的路口','夜间通过急弯、坡路、拱桥、人行横道、或没有交通信号灯控制的路口',5,1,4)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (30,'夜间通过急弯、坡路','夜间通过、急弯、坡路',5,1,4)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (31,'夜间通过坡路、拱桥','夜间通过、坡路、拱桥',5,1,4)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (32,'夜间通过拱桥、人行横道','夜间通过、拱桥，人行横道',5,1,4)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (33,'夜间通过急弯、拱桥','夜间通过、急弯，拱桥',5,1,4)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (34,'夜间通过没有交通信号灯控制的路口','夜间通过、没有交通信号灯控制的路口',5,1,4)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (15,'夜间在窄路与非机动车会车','夜间在窄路与非机动车会车',5,1,5)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (16,'雾天行驶','雾天行驶',5,1,6)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (17,'夜间在道路上发生故障，妨碍交通又难以移动','夜间在道路上发生故障，妨碍交通又难以移动',5,1,7)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (35,'夜间在道路上发生交通事故，妨碍交通又难以移动','夜间在道路上发生交通事故，妨碍交通又难以移动',5,1,7)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (18,'模拟夜间考试完成，请关闭所有灯光','模拟夜间考试完成，请关闭所有灯光',5,1,8)");
		db.execSQL("INSERT INTO zxt_item(itemid, name, tts, timeout, type, xuhao) VALUES (27,'夜间在窄桥与机动车会车','夜间在窄桥与机动车会车',5,1,9)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (0,0,'不绕车一周检查车辆外观及安全状况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (1,0,'打开车门前不观察后方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (2,1,'制动气压不足起步',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (3,1,'车门未关闭起步',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (4,1,'起步前，未通过后视镜并向左方侧头，观察左、后方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (5,1,'启动发动机时，变速器操纵杆未置于空挡(或者P挡)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (6,1,'发动机启动后，不及时松开启动开关',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (7,1,'不松驻车制动器起步',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (8,1,'道路交通情况复杂时起步不能合理使用喇叭',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (9,1,'起步时车辆发生闯动',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (10,1,'起步时，加速踏板控制不当，致使发动机转速过高',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (11,1,'启动发动机前，不调整驾驶座椅、后视镜、检查仪表',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (12,2,'方向控制不稳，不能保持车辆直线运动状态',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (13,2,'不了解车辆行驶速度',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (14,2,'未及时发现路面障碍物，未及时采取减速措施',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (15,3,'变更车道时，判断车辆安全距离不合理，妨碍其他车辆正常行驶',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (16,3,'连续变更两条以上车道',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (17,4,'通过路口前未减速慢行',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (18,4,'遇有路口交通阻塞时进入路口，将车辆停在路口内等候',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (19,4,'不按规定避让行人和优先通过的车辆',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (20,4,'左转通过路口时，未靠路口中心点左侧转弯',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (21,5,'不按规定减速慢行',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (22,5,'未停车礼让行人',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (23,6,'在没有中心隔离设施或者中心线的道路上会车时，不减速靠右行驶，并与其他车辆、行人或者非机动车未保持安全距离',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (24,6,'横向安全间距判断差，紧急转向避让相对方向来车',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (25,7,'超车时机选择不合理，影响其他车辆正常行驶',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (26,7,'超车时未与被超越车辆保持安全距离',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (27,7,'超车后急转向驶回本车道，妨碍被超车辆正常行驶',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (28,7,'从右侧超车',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (29,7,'当后车发出超车信号时，具备让车条件不减速靠右让行',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (30,8,'停车前，不通过内、外后视镜观察后方和右侧交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (31,8,'停车后，车身超过道路右侧边缘线或者人行道边缘',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (32,8,'停车后，在车内开门前不侧头观察侧后方和左侧交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (33,8,'停车后，车身距离道路右侧边缘线或者人行道边缘大于30厘米',20)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (34,8,'停车后，未拉紧驻车制动器',20)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (35,8,'拉紧驻车制动器前放松行车制动踏板',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (36,8,'下车后不关车门',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (37,8,'下车前不将发动机熄火',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (38,8,'夜间在路边临时停车不关闭前照灯或不开启警示灯',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (39,9,'不能正确观察交通情况选择掉头时机',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (40,9,'掉头地点选择不当',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (41,9,'掉头时，妨碍正常行驶的其他车辆和行人通行',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (43,13,'同方向近距离跟车行驶时，使用远光灯',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (44,14,'通过急弯、坡路、拱桥、人行横道或者没有交通信号灯控制的路口时，不交替使用远、近光灯示意',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (45,15,'会车时不按规定使用灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (49,11,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (50,12,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (51,13,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (52,14,'夜间通过坡路、拱桥时，没有交替使用远、近光灯示意',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (53,14,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (54,17,'在路边临时停车没有关闭前照灯(1)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (55,18,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (56,16,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (57,17,'在路边临时停车没有开启警示灯(2)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (58,17,'在路边临时停车没有开启警示灯(3)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (59,17,'在路边临时停车没有开启警示灯(4)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (60,17,'在路边临时停车没有关闭前照灯(5)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (61,21,'未按指令平稳加、减挡',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (62,21,'车辆运行速度和档位不匹配',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (63,3,'变更车道前，未通过内、外后视镜观察后方道路交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (64,3,'开启转向灯少于3秒',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (65,22,'变更车道时，判断车辆安全距离不合理，妨碍其他车辆正常行驶',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (66,22,'连续变更两条以上车道',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (67,22,'变更车道前，未通过内、外后视镜观察后方道路交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (68,22,'开启转向灯少于3秒',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (69,22,'未开启转向灯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (70,3,'未开启转向灯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (71,4,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (72,4,'转弯通过路口时，未观察侧前方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (73,23,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (74,23,'转弯通过路口时，未观察侧前方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (75,23,'未开启转向灯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (76,23,'开启转向灯少于3秒',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (77,23,'左转弯通过路口时，未靠路口中心点左侧转弯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (78,23,'遇有路口交通阻塞时进入路口，将车辆停在路口内等候',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (79,23,'未按规定减速或停车',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (80,24,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (81,24,'转弯通过路口时，未观察侧前方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (82,24,'未开启转向灯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (83,24,'开启转向灯少于3秒',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (84,24,'右转弯通过路口时，未靠路口中心点右侧转弯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (85,24,'遇有路口交通阻塞时进入路口，将车辆停在路口内等候',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (86,24,'未按规定减速或停车',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (87,5,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (88,25,'未按规定减速慢行',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (89,25,'未停车礼让行人',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (90,25,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (91,26,'未按规定减速慢行',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (92,26,'未停车礼让行人',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (93,26,'未观察左右方交通情况',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (94,9,'未开启转向灯',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (95,9,'0',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (96,8,'未开启转向灯，扣10分。',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (97,8,'开启转向灯，少于3秒，扣10分',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (98,8,'考试员发出靠边停车后，未能在规定距离内停车的，不合格。',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (99,8,'拉紧驻车制动器前，放松行车制动踏板的，扣10分。',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (100,8,'下车前不将发动机熄火的，扣5分。',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (101,8,'下车不关闭车门的，不合格。',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (102,15,'会车时不按规定使用灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (104,11,'不能正确开启灯光(雾灯未关闭)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (105,22,'未开启转向灯(考试过程中熄火)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (106,1,'车门未关闭起步(速度过高)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (107,1,'车门未关闭起步(转速未达到500)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (108,1,'车门未关闭起步(发动机未熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (109,1,'不松驻车制动器起步(未开转向灯)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (110,1,'起步时，加速踏板控制不当，致使发动机转速过高(车辆没有移动)',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (111,1,'不松驻车制动器起步(熄火)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (112,1,'不松驻车制动器起步(未开启转向灯)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (113,2,'不了解车辆行驶速度(未松手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (114,2,'不了解车辆行驶速度(车门未关闭)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (115,2,'不了解车辆行驶速度(熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (116,3,'未开启转向灯(行驶过程中熄火)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (117,3,'未开启转向灯(行驶过程中开启车门)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (118,3,'未开启转向灯(行驶过程拉起驻车制动)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (119,3,'未开启转向灯(未向左变更车道)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (120,22,'未开启转向灯(未开启右转向灯)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (121,22,'未开启转向灯(未向右变更车道)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (122,22,'未开启转向灯(车门未关)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (123,22,'未开启转向灯(未放驻车制动)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (124,22,'未开启转向灯(错误变道)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (125,3,'未开启转向灯(未向左变更车道)(错误变道)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (126,4,'通过路口前未减速慢行(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (127,4,'通过路口前未减速慢行(熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (128,4,'通过路口前未减速慢行(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (129,4,'通过路口前未减速慢行(脚刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (130,5,'不按规定减速慢行(脚刹2)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (131,4,'通过路口前未减速慢行(脚刹2)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (132,5,'不按规定减速慢行(熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (133,5,'不按规定减速慢行(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (134,5,'不按规定减速慢行(脚刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (135,5,'不按规定减速慢行(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (136,4,'通过路口前未减速慢行(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (137,4,'通过路口前未减速慢行(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (138,25,'未按规定减速慢行(熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (139,25,'未按规定减速慢行(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (140,25,'未按规定减速慢行(脚刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (141,25,'未按规定减速慢行(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (142,26,'未按规定减速慢行(熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (143,26,'未按规定减速慢行(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (144,26,'未按规定减速慢行(脚刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (145,26,'未按规定减速慢行(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (146,6,'在没有中心隔离设施或者中心线的道路上会车时，不减速靠右行驶，并与其他车辆、行人或者非机动车未保持安全距离(熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (147,6,'在没有中心隔离设施或者中心线的道路上会车时，不减速靠右行驶，并与其他车辆、行人或者非机动车未保持安全距离(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (148,6,'在没有中心隔离设施或者中心线的道路上会车时，不减速靠右行驶，并与其他车辆、行人或者非机动车未保持安全距离(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (149,7,'从右侧超车(左转)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (150,7,'从右侧超车(右转)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (151,7,'超车时未与被超越车辆保持安全距离(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (152,7,'超车时机选择不合理，影响其他车辆正常行驶(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (153,21,'未按指令平稳加、减挡(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (154,21,'未按指令平稳加、减挡(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (155,9,'不能正确观察交通情况选择掉头时机(熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (156,9,'未开启转向灯(左转灯)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (157,9,'不能正确观察交通情况选择掉头时机(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (158,9,'掉头时，妨碍正常行驶的其他车辆和行人通行(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (159,23,'未按规定减速或停车(熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (160,23,'未按规定减速或停车(发动机熄火或转速过高)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (161,23,'左转弯通过路口时，未靠路口中心点左侧转弯(左转角度无)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (162,23,'未开启转向灯(左转灯)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (163,23,'未按规定减速或停车(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (164,23,'未按规定减速或停车(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (165,23,'未按规定减速或停车(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (166,23,'未按规定减速或停车(脚刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (167,24,'未按规定减速或停车(熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (168,24,'未按规定减速或停车(转速)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (169,24,'未按规定减速或停车(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (170,24,'未按规定减速或停车(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (171,24,'未开启转向灯(左转灯)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (172,24,'未按规定减速或停车(脚刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (173,24,'未开启转向灯(右转灯)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (174,8,'考试员发出靠边停车后，未能在规定距离内停车的，不合格。(熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (175,8,'考试员发出靠边停车后，未能在规定距离内停车的，不合格。(角度)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (176,8,'考试员发出靠边停车后，未能在规定距离内停车的，不合格。(速度)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (177,8,'下车后不关车门(开门)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (178,8,'下车后不关车门(关门)',10)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (179,8,'下车前不将发动机熄火(点火信号)',5)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (180,30,'夜间通过坡路、拱桥时，没有交替使用远、近光灯示意',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (181,30,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (182,31,'夜间通过坡路、拱桥时，没有交替使用远、近光灯示意',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (183,31,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (184,32,'夜间通过坡路、拱桥时，没有交替使用远、近光灯示意',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (185,32,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (186,33,'夜间通过坡路、拱桥时，没有交替使用远、近光灯示意',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (187,33,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (188,34,'夜间通过坡路、拱桥时，没有交替使用远、近光灯示意',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (189,34,'不能正确开启灯光',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (204,35,'在路边临时停车没有关闭前照灯(1)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (207,35,'在路边临时停车没有开启警示灯(2)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (208,35,'在路边临时停车没有开启警示灯(3)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (209,35,'在路边临时停车没有开启警示灯(4)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (210,35,'在路边临时停车没有关闭前照灯(5)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (238,39,'未按规定减速慢行(熄火)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (239,39,'未按规定减速慢行(手刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (240,39,'未按规定减速慢行(脚刹)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (241,39,'未按规定减速慢行(车门)',100)");
		db.execSQL("INSERT INTO zxt_item_err(errid, itemid, name, fenshu) VALUES (242,39,'未按规定减速慢行',100)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (0,'随机路线(手动)','当前为随机路线,请点击考试项目开始考试',0)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (1,'模拟夜间灯光考试(手动)','下面将、进行模拟夜间行驶场景灯光、使用的考试，请按语音指令、在5秒内做出相应的灯光操作。请点击考试项目。',0)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (2,'模拟夜间灯光考试一(自动)','下面将、进行模拟夜间行驶场景灯光、使用的考试，请按语音指令、在5秒内做出相应的灯光操作',1)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (3,'模拟夜间灯光考试二(自动)','下面将、进行模拟夜间行驶场景灯光、使用的考试，请按语音指令、在5秒内做出相应的灯光操作',1)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (4,'模拟夜间灯光考试三(自动)','下面将、进行模拟夜间行驶场景灯光、使用的考试，请按语音指令、在5秒内做出相应的灯光操作',1)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (5,'模拟夜间灯光考试四(自动)','下面将、进行模拟夜间行驶场景灯光、使用的考试，请按语音指令、在5秒内做出相应的灯光操作',1)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (8,'沌口考场(左)','当前为沌口考场路线',1)");
		db.execSQL("INSERT INTO zxt_route(routeid, name, tts, auto) VALUES (9,'沌口考场(右)','当前为沌口考场路线',1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,0,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,1,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,2,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,3,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,4,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,5,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,6,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,7,0,0,8)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,9,0,0,9)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,21,0,0,10)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,22,0,0,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,23,0,0,12)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,24,0,0,13)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,25,0,0,14)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,26,0,0,15)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,27,0,0,16)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (0,8,0,0,17)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,11,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,12,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,13,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,14,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,30,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,31,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,32,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,33,0,0,8)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,34,0,0,9)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,15,0,0,10)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,16,0,0,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,17,0,0,12)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,35,0,0,13)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (1,18,0,0,14)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,11,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,12,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,13,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,34,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,12,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,15,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,17,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (2,18,0,0,8)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,11,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,12,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,15,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,30,0,0,8)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,35,0,0,10)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (3,18,0,0,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,11,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,12,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,15,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,31,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,16,0,0,8)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (4,18,0,0,9)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,11,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,12,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,12,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,15,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,17,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,18,0,0,8)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (5,32,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,0,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,1,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,2,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,3,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,22,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,9,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,6,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,7,0,0,8)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,21,0,0,9)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,8,0,0,10)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,26,	114.183348,	30.466603,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,25,	114.183632,	30.470603,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,36,	114.183394,	30.471998,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,23,	114.183423,	30.472671,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.183449	,30.473224 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.183045	,30.473601 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,26,	114.182483,	30.473823,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,25,	114.181284,	30.474095,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,38,	114.181284,	30.474095,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,4	,114.180885	,30.47419  ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.180533	,30.474278 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.180039	,30.474351 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,36,	114.177748,	30.474964,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,23,	114.177226,	30.475066,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.176742	,30.475166 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.175486	,30.472666 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,26,	114.175116,	30.471426,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.17489	,30.470711 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,25,	114.17489	,30.470711 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,38,	114.174298,	30.468696,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,4	,114.174145	,30.46817  ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.173946	,30.467579 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,26,	114.1731	,30.46492  ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,25,	114.172823,	30.464133,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.172005	,30.461526 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,26,	114.171851,	30.461023,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,36,	114.171496,	30.459878,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,23,	114.171303,	30.459258,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.17109	,30.458576 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,25,	114.172178,	30.458096,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,26,	114.17368	,30.458104 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,25,	114.17701	,30.458053 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,26,	114.179421,	30.458145,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,36,	114.18033	,30.458201 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,23,	114.180848,	30.458265,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.181385	,30.458321 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,5	,114.181773	,30.45862  ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,25,	114.182033,	30.459986,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (8,26,	114.182301,	30.46161 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,0,0,0,1)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,1,0,0,2)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,2,0,0,3)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,3,0,0,4)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,22,0,0,5)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,9,0,0,6)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,6,0,0,7)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,7,0,0,8)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,21,0,0,9)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,8,0,0,10)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,26,	114.182526,	30.462923,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,26,	114.182301,	30.46161 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,25,	114.18199	,30.459965 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,37,	114.181865,	30.459245,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,24,	114.181773,	30.45862 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.181773	,30.45862  ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.181385	,30.458321 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,26,	114.179583,	30.458225,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,25,	114.177663,	30.458155,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,25,	114.173737,	30.458148,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,26,	114.172816,	30.458158,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,37,	114.172816,	30.458158,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,24,	114.172121,	30.458146,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.171461	,30.458155 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,26,	114.171343,	30.458853,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.172018	,30.46113  ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,25,	114.172834,	30.463809,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,38,	114.173461,	30.465694,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,4	,114.173651	,30.46635  ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.173822	,30.466932 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,26,	114.17412	,30.46773  ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.174944	,30.47053  ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,25,	114.174944,	30.47053 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,39,	114.175423,	30.471985,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.175543	,30.47238  ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,26,	114.175543,	30.47238 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,37,	114.176037,	30.473912,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,24,	114.176161,	30.474335,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.17632	,30.474859 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,38,	114.179174,	30.474475,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,4	,114.179592	,30.474417 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.180039	,30.474351 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,25,	114.180575,	30.474161,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,26,	114.181978,	30.473854,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,37,	114.181978,	30.473854,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,24,	114.182648,	30.4737  ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.183045	,30.473601 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.183449	,30.473224 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,25,	114.183309,	30.472269,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,25,	114.183161,	30.467548,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,26,	114.183143,	30.466751,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,37,	114.18314	,30.466173 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,24,	114.18306	,30.465511 ,11)");
		db.execSQL("INSERT INTO zxt_route_item(routeid, itemid, lon, lat, xuhao) VALUES (9,5	,114.182976	,30.464909 ,11)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,12,2,0,0,3,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,12,-1,0,0,2,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,12,-1,0,0,7,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,21,0,0,5,2,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,20,0,0,500,2,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,5,-2,0,0,7,5)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,12,-1,0,0,10,5)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,20,0,500,0,111,5)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,5,1,0,0,113,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,12,-1,0,0,114,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,21,0,30,80,13,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,20,0,100,3000,115,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,5,1,0,0,113,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,12,-1,0,0,114,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,21,0,30,80,13,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,20,0,500,3000,115,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (2,31,0,-3,3,12,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (3,3,2,0,0,70,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (3,5,1,0,0,118,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (3,12,-1,0,0,117,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (3,20,0,500,3000,116,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (4,7,2,0,0,129,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (5,5,1,0,0,133,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (5,7,2,0,0,134,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (5,12,-1,0,0,135,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (5,20,0,500,3000,132,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,4,2,0,0,96,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,20,0,500,3000,174,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,20,0,500,3000,174,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,5,2,0,0,34,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,7,2,0,0,35,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,20,0,500,3000,174,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,5,2,0,0,34,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (9,3,2,0,0,156,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (9,5,1,0,0,157,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (9,12,-1,0,0,158,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (9,20,0,500,3000,155,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (11,0,2,0,0,49,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (11,1,2,0,0,49,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (11,2,-2,0,0,49,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (12,0,2,0,0,50,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (12,1,2,0,0,50,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (12,2,2,0,0,50,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (13,0,2,0,0,51,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (13,1,2,0,0,43,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (13,2,-2,0,0,43,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (13,9,-2,0,0,51,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,2,2,0,0,52,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,2,-2,0,0,52,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,2,2,0,0,52,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,0,2,0,0,53,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,1,2,0,0,53,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,2,-2,0,0,53,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (14,9,-2,0,0,53,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (15,0,2,0,0,102,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (15,1,2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (15,2,-2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (15,9,-2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,6,-2,0,0,56,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,6,2,0,0,56,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,6,-2,0,0,56,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,0,2,0,0,56,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,1,2,0,0,999,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,2,-2,0,0,56,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,6,2,0,0,56,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (16,9,2,0,0,56,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,6,-2,0,0,57,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,6,2,0,0,54,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,6,-2,0,0,57,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,0,2,0,0,60,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,1,-2,0,0,54,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,2,-2,0,0,54,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,6,2,0,0,59,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (17,9,-2,0,0,54,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (18,0,-2,0,0,55,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (18,1,-2,0,0,55,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (18,2,-2,0,0,55,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (18,6,-2,0,0,55,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (18,9,-2,0,0,55,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (21,5,1,0,0,153,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (21,12,-1,0,0,154,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (21,20,0,500,3000,61,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (22,4,2,0,0,120,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (22,7,1,0,0,123,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (22,12,-1,0,0,122,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (22,20,0,500,3000,105,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,5,1,0,0,163,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,12,-1,0,0,164,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,20,0,500,3000,160,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,5,1,0,0,169,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,12,-1,0,0,170,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (25,5,1,0,0,139,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (25,7,2,0,0,140,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (25,12,-1,0,0,141,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (25,20,0,500,3000,138,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (26,5,1,0,0,143,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (26,7,2,0,0,144,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (26,12,-1,0,0,145,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (26,20,0,500,3000,142,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (27,0,2,0,0,102,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (27,1,2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (27,2,-2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (27,9,-2,0,0,45,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (12,9,-2,0,0,50,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,20,0,0,3000,10,6)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,21,0,5,0,110,6)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,5,1,0,0,7,6)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,12,-1,0,0,3,6)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,3,2,0,0,112,5)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,7,2,0,0,2,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,21,0,0,5,106,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (22,31,0,0,-2,124,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (22,31,0,2,0,121,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (3,31,0,0,2,125,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (3,31,0,-2,0,119,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (4,20,0,500,3000,127,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (4,5,1,0,0,136,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (4,12,-1,0,0,137,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (6,20,0,500,3000,146,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (6,5,1,0,0,147,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (6,12,-1,0,0,148,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (7,20,0,500,3000,999,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (7,3,2,0,0,149,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (7,5,1,0,0,151,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (7,12,-1,0,0,152,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,3,2,0,0,75,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,7,2,0,0,166,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (23,31,0,-3,0,77,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,20,0,500,3000,168,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,4,2,0,0,173,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,7,2,0,0,172,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (24,31,0,3,0,84,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (8,31,0,3,0,175,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (4,7,2,0,0,17,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (5,7,2,0,0,21,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (25,7,2,0,0,88,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (26,7,2,0,0,91,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (1,12,2,0,0,3,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (18,6,1,0,0,55,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (30,2,2,0,0,180,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (30,2,-2,0,0,180,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (30,2,2,0,0,180,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (30,0,2,0,0,181,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (30,1,2,0,0,181,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (30,2,-2,0,0,181,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (30,9,-2,0,0,181,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (31,2,2,0,0,182,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (31,2,-2,0,0,182,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (31,2,2,0,0,182,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (31,0,2,0,0,183,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (31,1,2,0,0,183,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (31,2,-2,0,0,183,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (31,9,-2,0,0,183,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (32,2,2,0,0,184,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (32,2,-2,0,0,184,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (32,2,2,0,0,184,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (32,0,2,0,0,185,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (32,1,2,0,0,185,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (32,2,-2,0,0,185,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (32,9,-2,0,0,185,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (33,2,2,0,0,186,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (33,2,-2,0,0,186,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (33,2,2,0,0,186,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (33,0,2,0,0,187,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (33,1,2,0,0,187,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (33,2,-2,0,0,187,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (33,9,-2,0,0,187,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (34,2,2,0,0,188,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (34,2,-2,0,0,188,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (34,2,2,0,0,188,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (34,0,2,0,0,189,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (34,1,2,0,0,189,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (34,2,-2,0,0,189,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (34,9,-2,0,0,189,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (35,6,-2,0,0,207,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (35,6,2,0,0,204,2)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (35,6,-2,0,0,207,3)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (35,0,2,0,0,210,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (35,1,-2,0,0,204,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (35,2,-2,0,0,204,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (35,6,2,0,0,209,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (35,9,-2,0,0,204,4)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (36,12,2,0,0,999,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (37,12,2,0,0,999,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (38,12,2,0,0,999,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (39,5,1,0,0,239,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (39,7,2,0,0,240,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (39,12,-1,0,0,241,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (39,20,0,500,3000,238,1)");
		db.execSQL("INSERT INTO zxt_item_action(itemid,dataid,times,min,max,errid,step) VALUES (39,7,2,0,0,242,2)");

	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
		db.execSQL("DROP TABLE IF EXISTS " + T_ROUTE);
		db.execSQL("DROP TABLE IF EXISTS " + T_ROUTE_ITEM);
		db.execSQL("DROP TABLE IF EXISTS " + T_ITEM);
		db.execSQL("DROP TABLE IF EXISTS " + T_ITEM_ERR);
		db.execSQL("DROP TABLE IF EXISTS " + T_ITEM_ACTION);
		onCreate(db);
	}
}